version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    networks:
      - backend
      - frontend
    ports:
      - "80"
    restart: always
    volumes:
      - /var/www/html/wp-content/themes
      - wp_content:/var/www/html/wp-content 
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
      - frontend
    ports:
      - "80"
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db:3306
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress

networks:
  backend:
  frontend:
  
volumes:
  db_data:
  wp_content:
